export const vehicles = [
  {
    id: 'mercedes-s-class',
    brand: 'Mercedes-Benz',
    model: 'Classe S',
    tagline: 'La définition du luxe',
    price: '112 000',
    category: 'Berline de Luxe',
    fuel: 'Hybride',
    power: '367 ch',
    acceleration: '4.9s',
    speed: '250 km/h',
    color: '#1a1a2e',
    accent: '#c9a84c',
    features: ['MBUX Hyperscreen', 'Massage 5 zones', 'Suspension pneumatique', 'Drive Pilot'],
    image: '/images/classe-s.png',
    isElectric: false,
    isNew: true,
  },
  {
    id: 'mercedes-eqs',
    brand: 'Mercedes-Benz',
    model: 'EQS 580',
    tagline: "L'avenir électrique",
    price: '139 000',
    category: '100% Électrique',
    fuel: 'Électrique',
    power: '523 ch',
    acceleration: '4.3s',
    speed: '210 km/h',
    color: '#0d1117',
    accent: '#00d4ff',
    features: ["523 km d'autonomie", 'Charge 200kW', 'MBUX Hyperscreen 1.41m', 'EQ Power'],
    image: '/images/MercedesEQS580.png',
    isElectric: true,
    isNew: true,
  },
  {
    id: 'porsche-911',
    brand: 'Porsche',
    model: '911 Carrera S',
    tagline: 'Icône intemporelle',
    price: '148 000',
    category: 'Sport Légendaire',
    fuel: 'Essence',
    power: '450 ch',
    acceleration: '3.5s',
    speed: '308 km/h',
    color: '#1a0a0a',
    accent: '#e85d04',
    features: ['PDK 8 rapports', 'PASM Sport', 'Sport Chrono Package', 'Rear-Axle Steering'],
    image: '/images/porsche911.png',
    isElectric: false,
    isNew: false,
  },
  {
    id: 'porsche-taycan',
    brand: 'Porsche',
    model: 'Taycan Turbo S',
    tagline: 'Électrique, radical',
    price: '189 000',
    category: 'Électrique Sport',
    fuel: 'Électrique',
    power: '761 ch',
    acceleration: '2.8s',
    speed: '260 km/h',
    color: '#0a0a0a',
    accent: '#7b2d8b',
    features: ['800V Architecture', '0-100 en 2.8s', '2 moteurs électriques', 'Launch Control'],
    image: '/images/taycan-turbo-s.png',
    isElectric: true,
    isNew: true,
  },
  {
    id: 'mercedes-amg-gt',
    brand: 'Mercedes-AMG',
    model: 'GT 63 S',
    tagline: 'La bête de course',
    price: '174 000',
    category: 'Super Sport',
    fuel: 'Essence',
    power: '630 ch',
    acceleration: '3.2s',
    speed: '315 km/h',
    color: '#0f0f0f',
    accent: '#c9a84c',
    features: ['V8 Biturbo 4.0L', 'AMG Speedshift DCT 9G', 'AMG Ride Control+', 'Drift Mode'],
    image: '/images/gt63s.png',
    isElectric: false,
    isNew: false,
  },
  {
    id: 'porsche-cayenne',
    brand: 'Porsche',
    model: 'Cayenne Turbo GT',
    tagline: 'SUV sans compromis',
    price: '196 000',
    category: 'SUV Sport',
    fuel: 'Essence',
    power: '640 ch',
    acceleration: '3.3s',
    speed: '305 km/h',
    color: '#0a0a14',
    accent: '#e85d04',
    features: ['PASM Sport', 'Rear-Axle Steering 2.8°', 'Titanium Package', 'Nürburgring Record'],
    image: '/images/cayenne-turbo-gt.png',
    isElectric: false,
    isNew: true,
  },
];

export const getVehicleById      = (id) => vehicles.find(v => v.id === id);
export const getElectricVehicles = ()    => vehicles.filter(v => v.isElectric);
export const getMercedesVehicles = ()    => vehicles.filter(v => v.brand.includes('Mercedes'));
export const getPorscheVehicles  = ()    => vehicles.filter(v => v.brand === 'Porsche');